-- MySQL Script generated by MySQL Workbench
-- Fri Jul 22 15:32:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hiking_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hiking_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hiking_project` DEFAULT CHARACTER SET utf8 ;
USE `hiking_project` ;

-- -----------------------------------------------------
-- Table `hiking_project`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiking_project`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `nickname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `hiking_project`.`hikes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiking_project`.`hikes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `creation_date` DATE NULL,
  `distance` INT NULL,
  `duration` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `elevation_gain` INT NULL,
  `description` VARCHAR(255) NULL,
  `update` VARCHAR(255) NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hikes_users1_idx` (`user_id` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `hiking_project`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiking_project`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `hikes_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tags_hikes1_idx` (`hikes_id` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `hiking_project`.`medias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiking_project`.`medias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `file` VARCHAR(45) NULL,
  `hikes_id` INT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medias_hikes1_idx` (`hikes_id` ASC) VISIBLE)
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
